return {}
--
--local M = {
--    'williamboman/mason.nvim',
--    event = "BufAdd",
--    dependencies = {
--        'williamboman/mason-lspconfig.nvim',
--        'nvim-lua/plenary.nvim',
--    },
--}
--
----M.servers = {
--    --	"lua_ls",
--    --	"rust_analyzer",
--    --	"clangd"
--    --}
--
--    function M.config()
--        require("mason").setup()
--
--        require "mason-lspconfig".setup_handlers {
--            function (server_name)
--                require "lspconfig" [server_name].setup {}
--            end
--        }
--
--        require("mason-lspconfig").setup {
--            --            ensure_installed = M.servers,
--            automatic_installation = true,
--        }
--
--        vim.diagnostic.config({
--            virtual_text = true
--        })
--
--    end
--
--    return M
